#!/usr/bin/env bash
set -Eeuo pipefail

MOD_NAME="A Union Before Midnight V4.2"
SETTINGS_FILE=""
DEBUG_LOGS="${AUBM_DEBUG_LOGS:-0}"
RUNTIME_ROOT="${AUBM_RUNTIME_ROOT:-${XDG_DATA_HOME:-$HOME/.local/share}/aubm-deck}"
CONFIG_FILE="$RUNTIME_ROOT/config.env"

usage() {
    cat <<'EOF'
Usage: configure-aubm-deck.sh [options]

Options:
  --settings PATH   Darkest Hour settings.cfg path
  --mod-name NAME   Selected mod folder name
  --debug           Enable Darkest Hour extra debug logs
  --no-debug        Disable Darkest Hour extra debug logs (default)
  --help            Show this help
EOF
}

if [[ -f "$CONFIG_FILE" ]]; then
    # This file is generated by the installer with shell-escaped values.
    # shellcheck disable=SC1090
    source "$CONFIG_FILE"
    SETTINGS_FILE="${AUBM_SETTINGS_FILE:-$SETTINGS_FILE}"
    MOD_NAME="${AUBM_MOD_NAME:-$MOD_NAME}"
fi

while (($#)); do
    case "$1" in
        --settings)
            SETTINGS_FILE="${2:?--settings requires a path}"
            shift 2
            ;;
        --mod-name)
            MOD_NAME="${2:?--mod-name requires a name}"
            shift 2
            ;;
        --debug)
            DEBUG_LOGS=1
            shift
            ;;
        --no-debug)
            DEBUG_LOGS=0
            shift
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        *)
            printf 'Unknown option: %s\n' "$1" >&2
            usage >&2
            exit 2
            ;;
    esac
done

if [[ -z "$SETTINGS_FILE" && -n "${AUBM_GAME_ROOT:-}" ]]; then
    SETTINGS_FILE="$AUBM_GAME_ROOT/settings.cfg"
fi

if [[ ! -f "$SETTINGS_FILE" ]]; then
    printf 'Darkest Hour settings file not found: %s\n' "$SETTINGS_FILE" >&2
    exit 1
fi

if [[ "$DEBUG_LOGS" != 0 && "$DEBUG_LOGS" != 1 ]]; then
    printf 'AUBM_DEBUG_LOGS must be 0 or 1, got: %s\n' "$DEBUG_LOGS" >&2
    exit 1
fi

if [[ ! -f "$SETTINGS_FILE.aubm-original" ]]; then
    cp --preserve=mode,timestamps -- "$SETTINGS_FILE" "$SETTINGS_FILE.aubm-original"
fi

TEMP_FILE="$(mktemp "${SETTINGS_FILE}.aubm.XXXXXX")"
trap 'rm -f -- "$TEMP_FILE"' EXIT

awk -v mod_name="$MOD_NAME" -v debug_logs="$DEBUG_LOGS" '
function set_value(value) {
    marker = index($0, "#")
    if (marker > 0) {
        print value " " substr($0, marker)
    } else {
        print value
    }
}
/# Display resolution/        { set_value("6"); next }
/# Screen Width/              { set_value("1280"); next }
/# Screen Height/             { set_value("800"); next }
/# Display mode/              { set_value("0"); next }
/# Start-up movie/            { set_value("0"); next }
/# Extra debug logs/          { set_value(debug_logs); next }
/# Load game sounds/          { set_value("1"); next }
/# Load unit sprites/         { set_value("1"); next }
/# Load country specific/     { set_value("1"); next }
/# Refresh map/               { set_value("1"); next }
/# MODDIR folder/             { set_value("Mods"); next }
/# Selected mod/              { set_value(mod_name); next }
{ sub(/\r$/, ""); print }
' "$SETTINGS_FILE" > "$TEMP_FILE"

for expected in \
    '^6 # Display resolution' \
    '^1280 # Screen Width' \
    '^800 # Screen Height' \
    '^0 # Display mode' \
    "^${DEBUG_LOGS} # Extra debug logs" \
    "^${MOD_NAME//./\\.} # Selected mod"; do
    if ! grep -Eq -- "$expected" "$TEMP_FILE"; then
        printf 'settings.cfg does not contain the expected field: %s\n' "$expected" >&2
        exit 1
    fi
done

chmod --reference="$SETTINGS_FILE" "$TEMP_FILE" 2>/dev/null || true
mv -f -- "$TEMP_FILE" "$SETTINGS_FILE"
trap - EXIT

printf 'Configured Darkest Hour for Steam Deck: 1280x800, mod "%s", debug=%s\n' \
    "$MOD_NAME" "$DEBUG_LOGS"
