#!/usr/bin/env bash
set -Eeuo pipefail

RUNTIME_ROOT="${AUBM_RUNTIME_ROOT:-${XDG_DATA_HOME:-$HOME/.local/share}/aubm-deck}"
CONFIG_FILE="$RUNTIME_ROOT/config.env"
DEBUG_LOGS="${AUBM_DEBUG_LOGS:-0}"
CONFIGURE_ONLY=0

usage() {
    cat <<'EOF'
Usage: launch-aubm-deck [--debug] [--configure-only] -- %command%

Paste the launch option printed by install-aubm-deck.sh into Darkest Hour's
Steam properties. The wrapper preserves Proton's command and bypasses only the
Windows launcher executable.
EOF
}

if [[ -f "$CONFIG_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$CONFIG_FILE"
fi

while (($#)); do
    case "$1" in
        --debug)
            DEBUG_LOGS=1
            shift
            ;;
        --configure-only)
            CONFIGURE_ONLY=1
            shift
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        --)
            shift
            break
            ;;
        *)
            break
            ;;
    esac
done

"$RUNTIME_ROOT/bin/configure-aubm-deck" \
    $( [[ "$DEBUG_LOGS" == 1 ]] && printf '%s' '--debug' || printf '%s' '--no-debug' )

if ((CONFIGURE_ONLY)); then
    exit 0
fi

if (($# == 0)); then
    printf 'No Steam command was supplied. Use the launch option generated by the installer.\n' >&2
    exit 2
fi

command=("$@")
replacement_found=0
for index in "${!command[@]}"; do
    argument="${command[$index]}"
    lower_argument="${argument,,}"
    if [[ "$lower_argument" == *"darkest hour launcher.exe" ]]; then
        command[$index]="${argument:0:${#argument}-25}Darkest Hour.exe"
        replacement_found=1
    elif [[ "$lower_argument" == *"darkest hour.exe" ]]; then
        replacement_found=1
    fi
done

if ((replacement_found == 0)); then
    printf 'Steam command did not contain Darkest Hour Launcher.exe or Darkest Hour.exe.\n' >&2
    printf 'Received command:' >&2
    printf ' %q' "${command[@]}" >&2
    printf '\n' >&2
    exit 2
fi

"$RUNTIME_ROOT/bin/manage-aubm-saves" snapshot pre-launch || \
    printf 'Warning: pre-launch save snapshot failed. Launch will continue.\n' >&2

if [[ "$DEBUG_LOGS" == 1 ]]; then
    export PROTON_LOG=1
fi

set +e
"${command[@]}"
game_status=$?
set -e

"$RUNTIME_ROOT/bin/manage-aubm-saves" snapshot post-launch || \
    printf 'Warning: post-launch save snapshot failed.\n' >&2
exit "$game_status"
