"""One safety implementation for every registered coercive puppet exit.

Country rows contain routing only. Eligibility, war preservation, detachment,
puppet verification and reward timing are generated by identical functions.
Unknown puppet-exit chains fail compilation instead of escaping the checks.
"""
from dataclasses import dataclass
from dh_save_spans import parse,Node,replace
from generate_aubm_liberator import event,action
from aubm_liberator_v3 import TAGS

@dataclass(frozen=True)
class Exit:
    tag:str
    master:str
    withdrawals:tuple
    outcomes:tuple

EXITS=(Exit('U87','JAP',(9289851,9289904),(9289852,9289905)),
       Exit('U03','JAP',(9294014,),(9294015,)),
       Exit('SIA','JAP',(9297004,),(9297005,)))
BASE=9297200

def aa(ev):return [f.value for f in ev.fields if f.key=='action' or (f.key or '').startswith('action_')]
def body(text,n):
    return ' '.join(l.split('#',1)[0].strip() for l in text[n.start+1:n.end-1].splitlines()) if isinstance(n,Node) else ''
def prefix(p):return 'ind_exit_'+p.tag.lower()+'_'
def war(tag):return f'war = {{ country = IND country = {tag} }}'
def wars_survive(p):
    return war(p.master)+' '+' '.join(f'OR = {{ NOT = {{ flag = {prefix(p)}war_{t.lower()} }} {war(t)} }}' for t in TAGS if t not in ('IND',p.tag))
def detached(p):
    return f'exists = {p.tag} NOT = {{ ispuppet = {p.tag} participant = {{ country = {p.tag} value = 4 }} atwar = {p.tag} }} '+wars_survive(p)
def protected(p):
    return f'exists = {p.tag} puppet = {{ country = {p.tag} country = IND }} NOT = {{ {war(p.tag)} }} '+wars_survive(p)
def gate_edit(text,n,gate):
    t=n.get('trigger')
    return (t.start+1,t.start+1,'\n'+gate+'\n') if isinstance(t,Node) else (n.start+1,n.start+1,'\n trigger = { '+gate+' }\n')

def transform(text,policies=EXITS):
    root=parse(text);events={int(e.get('id')):e for e in root.all('event')}
    actual={eid for eid,e in events.items() if any({'end_puppet','leave_alliance'} <= {c.get('type') for c in a.all('command')} for a in aa(e))}
    expected={i for p in policies for i in p.withdrawals}
    if actual!=expected:raise ValueError(f'Puppet exit coverage changed: actual={actual}, registered={expected}')
    edits=[];extra=[];callback=BASE
    for p in policies:
        for eid in p.withdrawals:
            e=events[eid]
            assert e.get('country')==p.tag
            for a in aa(e):
                commands=a.all('command')
                if not any(c.get('type')=='end_puppet' for c in commands):continue
                # Snapshot before the engine changes the defeated country's war
                # list. Clear stale records from a refused/previous attempt.
                snapshot=[]
                for t in TAGS:
                    if t in ('IND',p.tag):continue
                    f=prefix(p)+'war_'+t.lower()
                    snapshot += [f'command = {{ type = clrflag which = {f} }}',
                        f'command = {{ trigger = {{ {war(t)} }} type = setflag which = {f} }}']
                first=next(f for f in a.fields if f.key=='command')
                edits.append((first.start,first.start,'\n'+'\n'.join(snapshot)+'\n'))
        for eid in p.outcomes:
            e=events[eid];assert e.get('country')=='IND'
            common=detached(p)
            # Automatic notices and decision visibility use the same rule;
            # action gates also protect direct/queued event calls.
            edits.append(gate_edit(text,e,common))
            d=e.get('decision')
            if isinstance(d,Node):edits.append((d.start+1,d.start+1,'\n'+common+'\n'))
            for a in aa(e):
                cs=a.all('command')
                if not cs:continue
                pending=prefix(p)+'verifying'
                if all(c.get('type')=='clrflag' for c in cs):
                    # Retain the harmless failure exit and widen it when any
                    # new shared check fails. Never gate an exit on success.
                    old=a.get('trigger')
                    if isinstance(old,Node):
                        edits.append((old.start,old.end,'{ OR = { '+body(text,old)+' NOT = { AND = { '+common+' } } } }'))
                    continue
                edits.append(gate_edit(text,a,common+f' NOT = {{ flag = {pending} }}'))
                make=next((c for c in cs if c.get('type')=='make_puppet' and c.get('which')==p.tag),None)
                if make is None:continue
                # Preserve commands exactly, but pay/record only after the
                # engine has actually created the requested Indian puppet.
                deferred=[]
                for cf in [f for f in a.fields if f.key=='command']:
                    if cf.value is make:continue
                    deferred.append(body(text,cf.value))
                    edits.append((cf.start,cf.end,''))
                edits.append((a.end-1,a.end-1,
                    f'\n command = {{ type = setflag which = {pending} }}\n'
                    f'command = {{ type = event which = {callback} where = IND when = 1 }}\n'))
                valid=f'flag = {pending} '+protected(p)
                # action() accepts raw conditional commands or a type-less
                # command body; remove only the initial type= spelling.
                import re
                payload=[s if s.lstrip().startswith('trigger') else re.sub(r'^\s*type\s*=\s*','',s,count=1) for s in deferred]
                extra.append(event(callback,'Verify the new protected government',
                    'Confirm the Indian puppet relationship and every recorded unrelated Indian war before awarding the existing settlement. If a check fails, no reward is paid and no war is declared to hide the problem.',
                    [action('Confirm the government and existing rewards',*payload,f'clrflag which = {pending}',gate=valid,chance=100),
                     action('Verification failed - withhold the rewards',f'clrflag which = {pending}',gate='NOT = { AND = { '+valid+' } }',chance=100)]))
                callback+=1
            if not any(not a.all('command') or all(c.get('type')=='clrflag' for c in a.all('command')) for a in aa(e)):
                edits.append((e.end-1,e.end-1,'\n action = { name = "Close - the settlement checks did not pass" trigger = { NOT = { AND = { '+common+' } } } }\n'))
    return replace(text,edits)+'\n\n# Shared withdrawal verification\n'+'\n\n'.join(extra)+'\n'
