#!/usr/bin/env python3
"""LIBERATOR3: opt-in events embedded in an existing save-loaded module.

Owns the marked suffix and seven allowlisted, fixture-backed legacy events.
Other legacy bytes and all save/index/scenario files are preserved.
"""
from __future__ import annotations

import argparse
from dataclasses import dataclass
from itertools import combinations
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'mod/db/events/aubm_v4/43_wartime_settlements.txt'
MARKER = '# BEGIN AUBM LIBERATOR1 - generated by tools/generate_aubm_liberator.py'
P = 'ind_lib1_'


def flag(key): return f'flag = {P}{key}'
def no(expr): return f'NOT = {{ {expr} }}'
def all_of(*xs): return 'AND = { ' + ' '.join(xs) + ' }'
def any_of(*xs): return 'OR = { ' + ' '.join(xs) + ' }'
def war(tag): return f'war = {{ country = IND country = {tag} }}'
def control(prov, tag): return f'control = {{ province = {prov} data = {tag} }}'
def owned(prov, tag): return f'owned = {{ province = {prov} data = {tag} }}'
def puppet(tag, master): return f'puppet = {{ country = {tag} country = {master} }}'
def alliance(tag): return f'alliance = {{ country = IND country = {tag} }}'
def setf(key): return f'setflag which = {P}{key}'
def clear(key): return f'clrflag which = {P}{key}'
def later(eid, tag='IND', days=1): return f'event which = {eid} where = {tag} when = {days}'
def friendly_control(prov, tag): return any_of(control(prov, tag), control(prov, 'IND'))
def independent(tag): return all_of(f'exists = {tag}', no(f'ispuppet = {tag}'), no(war(tag)), no(f'alliance = {{ country = {tag} country = JAP }}'))


SOVEREIGN = all_of('flag = ind_aubm_route_sovereign', no('ispuppet = IND'),
                  *(no(alliance(t)) for t in ('ENG', 'GER', 'SOV', 'JAP', 'USA')),
                  *(no(f'flag = ind_aubm_commitment_{r}') for r in ('allied', 'german', 'soviet', 'japan')))
ACTIVE = all_of(flag('enabled'), SOVEREIGN)
HUMAN = 'ai = no'
PICTURE = 'aubm_v4_liberated_territory'


@dataclass(frozen=True)
class Action:
    name: str
    commands: tuple[str, ...] = ()
    gate: str = ''
    chance: int | None = None


def action(name, *commands, gate='', chance=None): return Action(name, commands, gate, chance)
CANCEL = action('Cancel - close without changes')


def event(eid, name, desc, actions, *, gate='', decision=False, country='IND', offset=2, automatic=False, save_date=False):
    lines = ['event = {', f'\tid = {eid}', '\trandom = no', '\tpersistent = yes', f'\tcountry = {country}']
    if automatic: lines.append('\tone_action = yes')
    if save_date: lines.append('\tsave_date = yes')
    if decision:
        lines += [f'\tdecision = {{ {HUMAN} {gate} }}', f'\ttrigger = {{ {HUMAN} {gate} }}']
    elif gate:
        lines.append(f'\ttrigger = {{ {gate} }}')
    lines += [f'\tname = "{name}"', f'\tdesc = "{desc}"', '\tstyle = 2', f'\tpicture = "{PICTURE}"']
    if gate:
        lines += ['\tdate = { day = 0 month = january year = 1940 }', f'\toffset = {offset}', '\tdeathdate = { day = 29 month = december year = 1964 }']
    for index, a in enumerate(actions):
        # DH 1.05.2 accepts the four legacy names action_a-d only. Additional
        # buttons use repeatable plain `action` blocks, NOT action_e, action_f...
        key = f'action_{chr(97 + index)}' if index < 4 else 'action'
        lines += [f'\t{key} = {{']
        if a.gate: lines.append(f'\t\ttrigger = {{ {a.gate} }}')
        if a.chance is not None: lines.append(f'\t\tai_chance = {a.chance}')
        lines.append(f'\t\tname = "{a.name}"')
        for c in a.commands:
            # Conditional commands carry their trigger outside the type clause.
            lines.append(f'\t\tcommand = {{ {c if c.startswith("trigger =") else "type = " + c} }}')
        lines.append('\t}')
    return '\n'.join(lines + ['}'])


@dataclass(frozen=True)
class Region:
    key: str
    title: str
    tag: str
    owners: tuple[str, ...]
    minimum: tuple[int, ...]
    hubs: tuple[int, ...]
    base: int


# Minimum release territory checked against the installed DH Full Map_1 revolt.txt.
REGIONS = (
    Region('malaya', 'Malaya', 'MLY', ('ENG',), (1435, 1436, 1437, 1438, 1433, 1434), (1432, 1438), 9289810),
    Region('dei', 'Indonesia', 'INO', ('U05', 'HOL'), (1648, 1651, 1649, 1654, 1653, 1655, 1656), (1647,), 9289820),
    Region('indochina', 'Vietnam', 'VIE', ('U03', 'FRA'), (1395, 1396, 1397, 1399, 1403), (1395, 1399), 9289830),
    Region('philippines', 'the Philippines', 'PHI', ('USA',), tuple(range(1565, 1581)), (1565, 1579), 9289840),
)


def liberation(r): return f'flag = ind_aubm_sea_land_{r.key}_liberated'


def release_gate(r, owner):
    provinces = tuple(dict.fromkeys(r.minimum + r.hubs))
    complete = all_of(no(f'exists = {r.tag}'),
        *(owned(p, owner) for p in provinces),
        *(friendly_control(p, owner) for p in provinces))
    existing = all_of(puppet(r.tag, owner), *(owned(p, r.tag) for p in r.hubs),
                      *(friendly_control(p, r.tag) for p in r.hubs))
    return all_of(ACTIVE, flag('japan_war'), liberation(r), f'exists = {owner}',
                  no(war(owner)), no(f'alliance = {{ country = {owner} country = JAP }}'),
                  any_of(complete, existing))


def partner_gate(r):
    return all_of(ACTIVE, flag('japan_war'), liberation(r), independent(r.tag),
                  *(owned(p, r.tag) for p in r.hubs), *(friendly_control(p, r.tag) for p in r.hubs))


def regions():
    result = []
    for r in REGIONS:
        pending, cooldown = f'{r.key}_petition', f'{r.key}_cooldown'
        for n, owner in enumerate(r.owners):
            request, response = r.base + n * 2, r.base + n * 2 + 1
            can_offer = all_of(release_gate(r, owner), no(flag(pending)), no(flag(cooldown)), no(flag(f'{r.key}_partner')))
            live = all_of(release_gate(r, owner), flag(pending))
            result.append(event(request, f'Liberty Petition: {r.title}',
                f'Ask {owner} to recognise an independent {r.title}. Requires the earlier Indian liberation record and the complete minimum territory, restored to its legal owner or held by India. No friendly territory is seized. Cost: 100 money. Acceptance 65%, refusal 35%; a refusal allows a new petition after 180 days. Vietnam covers Vietnam, not Laos or Cambodia.',
                [action('Submit the independence petition: -100 money', 'money value = -100', setf(pending), later(response, owner, 3), gate=all_of(can_offer, 'money = 100')), CANCEL],
                gate=can_offer, decision=True))
            result.append(event(response, f'Delhi Requests Independence for {r.title}',
                'India has helped drive out Japan and asks for a sovereign settlement. Acceptance releases only legally owned territory through the normal country-release rules, or ends our existing mastery. No Indian division changes allegiance. The future government chooses its own cooperation with Delhi.',
                [action('Accept independence', clear(pending), setf(f'{r.key}_consent'),
                        f'trigger = {{ {no(f"exists = {r.tag}")} }} type = independence which = {r.tag} value = 1 when = 0',
                        f'trigger = {{ {puppet(r.tag, owner)} }} type = end_mastery which = {r.tag}',
                        gate=live, chance=65),
                 action('Refuse for now; reconsider after 180 days', clear(pending), setf(cooldown), later(r.base+8, days=180), gate=live, chance=35),
                 action('The proposal is no longer valid', clear(pending), gate=no(live), chance=100)], country=owner))
        available = all_of(partner_gate(r), no(flag(f'{r.key}_partner')), no(flag(f'{r.key}_treaty_pending')), no(flag(cooldown)))
        live_treaty = all_of(partner_gate(r), flag(f'{r.key}_treaty_pending'), no(flag(f'{r.key}_partner')))
        result.append(event(r.base+4, f'Equal Reconstruction Treaty: {r.title}',
            f'Offer a sovereign {r.title} reconstruction aid, not Indian rule. Cost: 200 money and 500 supplies. Acceptance 75%: military access to India, mutual goodwill and an Indian guarantee, plus a one-time +1 TC modifier and -1 dissent. Refusal 25%: aid is still delivered; retry after 180 days. Neither choice joins an alliance or declares war.',
            [action('Offer reconstruction and equal partnership', 'money value = -200', 'supplies value = -500', setf(f'{r.key}_treaty_pending'), later(r.base+5, r.tag, 3), gate=all_of(available, 'money = 200', 'supplies = 500')), CANCEL],
            gate=available, decision=True))
        result.append(event(r.base+5, f'{r.title}: An Equal Partner, Not a Puppet',
            'Indian reconstruction aid has arrived. Accepting grants India military access but no control over our diplomacy, armed forces or territory. Refusal retains the aid and our independence.',
            [action('Accept the equal partnership', clear(f'{r.key}_treaty_pending'), setf(f'{r.key}_partner'), 'money value = 200', 'supplies value = 500', 'access which = IND', 'relation which = IND value = 50',
                    f'guarantee which = IND where = {r.tag}', gate=live_treaty, chance=75),
             action('Accept aid, decline the military treaty', clear(f'{r.key}_treaty_pending'), 'money value = 200', 'supplies value = 500', setf(cooldown), later(r.base+8, days=180), gate=live_treaty, chance=25),
             action('The proposed treaty is no longer valid', clear(f'{r.key}_treaty_pending'), gate=no(live_treaty), chance=100)], country=r.tag))
        reward = all_of(partner_gate(r), flag(f'{r.key}_partner'), no(flag(f'{r.key}_reward')))
        result.append(event(r.base+6, f'{r.title} Signs the Delhi Partnership',
            'Independence has become a working relationship: access, reconstruction and an Indian security guarantee, with no annexation or alliance. India gains a one-time +1 TC modifier and -1 dissent. This counts toward the southern peace settlement.',
            [action('Record an equal sovereign partner', setf(f'{r.key}_reward'), 'tc_mod value = 1', 'dissent value = -1', gate=reward)], gate=reward, automatic=True))
        result.append(event(r.base+8, f'{r.title}: Diplomatic Review Available',
            'The cooling-off period has ended. A fresh petition or treaty still requires the current ownership, independence and liberation conditions.',
            [action('End this cooling-off period', clear(cooldown), gate=flag(cooldown))]))
    return result


CHINA_HUBS = (1337, 1338, 1317)  # Nanjing, Shanghai, Wuhan on DH Full Map_1.
CHINA_RETURN = (1337, 1317)  # Shanghai belongs to JAP in the user's August save.
CHINA_LEVERAGE = all_of(ACTIVE, flag('japan_war'), war('JAP'), war('U87'),
    puppet('U87', 'JAP'), 'alliance = { country = U87 country = JAP }',
    no('exists = CHI'), *(owned(p, 'U87') for p in CHINA_RETURN),
    *(control(p, 'IND') for p in CHINA_HUBS))
CHINA_FREE = all_of(independent('U87'), no('puppet = { country = U87 country = JAP }'),
                   *(owned(p, 'U87') for p in CHINA_RETURN), *(control(p, 'U87') for p in CHINA_RETURN))


def china():
    available = all_of(CHINA_LEVERAGE, no(flag('china_pending')), no(flag('china_protection_pending')), no(flag('china_cooldown')), no(flag('china_break')))
    live = all_of(CHINA_LEVERAGE, flag('china_pending'))
    reward = all_of(ACTIVE, flag('china_break'), CHINA_FREE, no(flag('china_reward')))
    return [event(9289850, 'Nanjing Must Choose: Tokyo or Chinese Sovereignty',
        'Hold Nanjing, Shanghai and Wuhan as India while fighting Japan and its Nanjing puppet. Offer a Chinese exit from Tokyo: 60% acceptance, 40% refusal. Cost: 250 money and 750 supplies. Acceptance ends Japanese mastery and all wars inherited by the Chinese government from its alliance. India stays at war with Japan. This preserves the Nanjing government and its units; it does not resurrect Chiang or annex China.',
        [action('Offer sovereignty and a separate Chinese peace', 'money value = -250', 'supplies value = -750', setf('china_pending'), later(9289851, 'U87', 3), gate=all_of(available, 'money = 250', 'supplies = 750')), CANCEL], gate=available, decision=True),
        event(9289851, 'The Nanjing Government Faces the Indian Terms',
        'Three central Chinese cities are in Indian hands. Delhi offers an end to Japanese mastery and a separate peace. Acceptance preserves this Chinese state, returns its occupied territory through peace, grants India access, and does not put China into an Indian alliance or a new war.',
        [action('Break with Tokyo and accept sovereignty', clear('china_pending'), setf('china_break'), 'end_puppet', 'leave_alliance when = 1', 'access which = IND', 'relation which = IND value = 100', gate=live, chance=60),
         action('Remain with Tokyo; reconsider in 90 days', clear('china_pending'), setf('china_cooldown'), later(9289853, days=90), gate=live, chance=40),
         action('India no longer holds the proposed leverage', clear('china_pending'), gate=no(live), chance=100)], country='U87'),
        event(9289852, 'A Chinese Government Leaves the Japanese System',
        'The Nanjing state is independent, outside the Japanese alliance, at peace with India and back in control of Nanjing and Wuhan. Japan-owned ports such as Shanghai are not transferred by this Chinese settlement: their fate belongs to the Japanese war. India gains 1,500 supplies, +2 TC modifier and -3 dissent once.',
        [action('Guarantee Chinese sovereignty', setf('china_reward'), 'guarantee which = IND where = U87', 'supplies value = 1500', 'tc_mod value = 2', 'dissent value = -3', gate=reward)], gate=reward, automatic=True),
        event(9289853, 'The Chinese Offer Can Be Reconsidered', 'A renewed offer still requires all three cities and the continuing Japanese puppet relationship.', [action('End the negotiation cooldown', clear('china_cooldown'), gate=flag('china_cooldown'))])]


SUEZ_CONTROL = all_of(*(any_of(*(control(p, t) for t in ('ENG', 'EGY', 'IND'))) for p in (900, 791)), no(war('ENG')), no(war('EGY')))
SUEZ_GARRISON = any_of(*(f'garrison = {{ country = IND province = {p} type = land size = 3 area = no }}' for p in (900, 791)))
AXIS_WAR = any_of(war('GER'), war('ITA'))
SUEZ_VALID = all_of(ACTIVE, AXIS_WAR, SUEZ_CONTROL, SUEZ_GARRISON)
SUEZ_THREAT = any_of(*(all_of(war(t), any_of(*(control(p,t) for p in (783, 789, 787)))) for t in ('GER','ITA')))


def suez():
    start = all_of(SUEZ_VALID, SUEZ_THREAT, no(flag('suez_watch')), no(flag('suez_reward')))
    invalid = all_of(flag('suez_watch'), no(flag('suez_invalid')), no(SUEZ_VALID))
    due = all_of(flag('suez_watch'), flag('suez_due'))
    good = all_of(due, SUEZ_VALID, no(flag('suez_invalid')), no(flag('suez_reward')))
    return [event(9289860, 'Indian Troops Take Up the Canal Defence',
        'Axis troops hold El Alamein, Alexandria or Cairo, and India is at war with the threatening power. Keep at least three Indian land divisions in Suez or Port Said for 30 days, with both canal provinces controlled by India, Britain or Egypt. Losing the position, leaving the war or removing the garrison fails this attempt. This is a sustained defensive deployment, not a claim to count individual battles.',
        [action('Begin the 30-day defence record', setf('suez_watch'), clear('suez_invalid'), clear('suez_due'), later(9289862, days=30), gate=start)], gate=start, automatic=True, offset=1),
        event(9289861, 'The Canal Defence Record Was Interrupted', 'This attempt cannot earn the defence reward. Another attempt can begin after the original 30-day review, if the Axis threat returns and the requirements are restored.',
        [action('Mark this attempt interrupted', setf('suez_invalid'), gate=invalid)], gate=invalid, automatic=True, offset=1),
        event(9289862, 'The Canal Defence Review Is Due', 'Review the completed observation period.',
        [action('Make the defence record ready for review', setf('suez_due'), gate=flag('suez_watch'))]),
        event(9289863, 'India Keeps the Canal Open',
        'The canal remained in friendly hands and Indian troops maintained the required deployment through the 30-day review. Britain need not surrender ownership for India to earn recognition: +1,500 supplies, +150 money, +1 TC modifier and -2 dissent, once. No alliance, declaration or province transfer occurs.',
        [action('Record the independent defence of Suez', setf('suez_reward'), clear('suez_watch'), clear('suez_due'), 'supplies value = 1500', 'money value = 150', 'tc_mod value = 1', 'dissent value = -2', gate=good)], gate=good, automatic=True, offset=1),
        event(9289864, 'The Canal Review Closes Without an Award', 'The defence requirements were not maintained. No reward is paid; the record is cleared for a future attempt.',
        [action('Close the failed attempt', clear('suez_watch'), clear('suez_due'), clear('suez_invalid'), gate=all_of(due, any_of(flag('suez_invalid'), no(SUEZ_VALID))))],
        gate=all_of(due, any_of(flag('suez_invalid'), no(SUEZ_VALID))), automatic=True, offset=1)]


CA = ('TRK', 'UZB', 'TAJ', 'KYG', 'KAZ')
CA_FREE = any_of(*(any_of(independent(t), all_of(puppet(t, 'IND'), no(war(t)))) for t in CA))


def settlements():
    from aubm_liberator_v3 import INDO_PARTNER
    ca = all_of(ACTIVE, flag('soviet_war'), no(war('SOV')), any_of('flag = ind_aubm_settlement_central_asia_sovereign', 'flag = ind_aubm_settlement_central_asia_protected'), CA_FREE, no(flag('ca_reconstruction')))
    partners = [any_of(all_of(flag(f'{r.key}_reward'), partner_gate(r)), INDO_PARTNER)
                if r.key == 'indochina' else all_of(flag(f'{r.key}_reward'), partner_gate(r)) for r in REGIONS]
    partners.append(any_of(all_of(flag('china_reward'), CHINA_FREE), all_of(flag('china_protectorate'), puppet('U87', 'IND'), no(war('U87')))))
    two = any_of(*(all_of(a,b) for a,b in combinations(partners,2)))
    south = all_of(ACTIVE, flag('japan_war'), no(war('JAP')), 'flag = ind_aubm_sea_theatre_achieved', two, no(flag('southern_peace')))
    final = all_of(ACTIVE, 'atwar = no', flag('southern_peace'), flag('ca_reconstruction'), CA_FREE, two, no(flag('two_front_peace')))
    return [event(9289870, 'Reconstruction Beyond the Soviet Frontier',
        'The Central Asian settlement has ended the Indian-Soviet war. At least one republic remains friendly and sovereign or an Indian puppet. Fund reconstruction: -300 money, -1,000 supplies, +1 research, +2 supply output and -2 dissent. This pays once, not per republic. The deeper LIBERATOR2 victory unlocks a separate development choice. Japan may still be at war with India.',
        [action('Fund Central Asian reconstruction', setf('ca_reconstruction'), 'money value = -300', 'supplies value = -1000', 'research_mod value = 1', 'industrial_modifier which = supplies value = 2', 'dissent value = -2', gate=all_of(ca,'money = 300','supplies = 1000')), CANCEL], gate=ca, decision=True),
        event(9289871, 'The Southern Peace Has Independent Signatories',
        'India has ended its Japanese war, completed the Southeast Asian operational theatre, and retained two live partners. A consenting Indian Chinese protectorate can count in place of sovereign China. +750 supplies, +250 money and -2 dissent. This completes the liberation-based World Balancer path; invading Japan itself is optional. It does not award a second primary charter.',
        [action('Record a peace with independent partners', setf('southern_peace'), 'supplies value = 750', 'money value = 250', 'dissent value = -2', gate=south)], gate=south, automatic=True),
        event(9289872, 'Delhi Conference: The Two-Front Settlement',
        'The southern peace and Central Asian reconstruction are complete, India is at peace, and the participating states remain sovereign partners or Indian puppets. Choose one additional, once-only legacy. Protectorates are not full independence. The normal charter congress remains separate; this conference resets no earlier reward. Suez is not required.',
        [action('Open community: +2 research, +3 supply output', setf('two_front_peace'), 'research_mod value = 2', 'industrial_modifier which = supplies value = 3', 'dissent value = -3', gate=final),
         action('A defensive logistics network: +3 TC, +2,500 supplies', setf('two_front_peace'), 'tc_mod value = 3', 'supplies value = 2500', 'dissent value = -1', gate=final), CANCEL], gate=final, decision=True)]


def manpower():
    years = any_of(*(all_of(f'year = {y}', no(f'year = {y+1}'), no(flag(f'replacement_{y}'))) for y in range(1940,1965)))
    gate = all_of(ACTIVE, any_of(war('JAP'), war('SOV')), 'army = 100', no('manpower = 400'), years)
    year_commands = tuple(f'trigger = {{ year = {y} {no(f"year = {y+1}")} }} type = {setf(f"replacement_{y}")}' for y in range(1940,1965))
    return [event(9289880, 'Wartime Replacement Training: LIBERATOR1',
        'For an independent Indian war against Japan or the USSR, an army of at least 100 divisions may train one additional replacement class each calendar year while manpower is below 400. Cost: 900 supplies, 100 money and +1 dissent; gain 180 manpower. It supplements existing reserves without replacing them. Two enemies do not create two annual classes. This is trained manpower, not a free new division.',
        [action('Equip this year\'s replacement class: +180 manpower', *year_commands, 'supplies value = -900', 'money value = -100', 'dissent value = 1', 'manpowerpool value = 180', gate=all_of(gate, 'supplies = 900','money = 100')), CANCEL], gate=gate, decision=True)]


def abandoned_requests():
    conditions, commands = [], []
    for r in REGIONS:
        for pending, valid in ((f'{r.key}_petition', any_of(*(release_gate(r,t) for t in r.owners))),
                               (f'{r.key}_treaty_pending', partner_gate(r))):
            bad = all_of(flag(pending), no(valid))
            conditions.append(bad)
            commands.append(f'trigger = {{ {bad} }} type = {clear(pending)}')
    bad = all_of(flag('china_pending'), no(CHINA_LEVERAGE))
    conditions.append(bad)
    commands.append(f'trigger = {{ {bad} }} type = {clear("china_pending")}')
    return event(9289890, 'Liberation Diplomacy: Close Invalid Proposals',
        'A recipient disappeared, the front changed, or India left the sovereign route. Clear only proposals that are no longer legal. No sovereignty, resources, completed credit or valid proposal is changed. A dispatched diplomatic mission is not refunded.',
        [action('Close only invalid proposals', *commands)], gate=any_of(*conditions), automatic=True, offset=1)


def render():
    optin = all_of('year = 1940', SOVEREIGN, no(flag('enabled')))
    ev = [event(9289800, 'LIBERATOR1 - India\'s Liberation Programme',
        'Optional extension for your existing save. Stay sovereign and choose when to fight Japan. Liberation can lead to negotiated independence and equal treaties. A Chinese break with Tokyo, sustained Suez defence and sovereign Central Asian reconstruction have distinct outcomes. Enabling changes no history, alliances or resources; it declares no war and repays no old mobilisation. The Liberation Campaign Guide remains available at peace and war.',
        [action('Enable the sovereign-liberator campaign', setf('enabled'), gate=optin), CANCEL], gate=optin, decision=True),
        event(9289801, 'LIBERATOR1 - Liberation Campaign Guide',
        'This guide is informational and never spends resources or changes your route. New choices appear as separate decisions when their real conditions are met. Waiting for Japan to attack Britain or America does not automatically put neutral India at war. Choose World Balancer in your wartime charter for this campaign. Treaties preserve foreign sovereignty and do not join an alliance.',
        [action('Read the southern liberation objectives', later(9289802)), action('Read China, Suez and Central Asia objectives', later(9289803)), action('Read the required independence territories', later(9289806)), CANCEL], gate=all_of(flag('enabled'), HUMAN), decision=True),
        event(9289802, 'Liberation Guide: Southern Settlements',
        'Retake Japanese-occupied hubs with an Indian contribution: Singapore and Kuala Lumpur; Batavia; Hanoi and Saigon; Manila and Davao. Earn liberation recognition, restore the full release territory, petition its owner, then offer an equal treaty. The operational theatre needs two land results plus one sea lane, or one land plus two sea lanes. End the Japan war and retain two sovereign partners for the southern peace dividend. Vietnam does not include Laos or Cambodia.', [CANCEL]),
        event(9289803, 'Liberation Guide: Wider Objectives',
        'China: hold Nanjing, Shanghai and Wuhan while fighting Japan and its Nanjing puppet to offer a break with Tokyo. The Nanjing state becomes independent; Chiang is not resurrected. Japan-owned Shanghai is not transferred by China. After a southern peace and Central Asian reconstruction, end all Indian wars for the two-front conference. The following pages explain Suez and northern manpower planning.',
        [action('Read the canal defence requirements', later(9289807)), action('Read the Soviet and replacement requirements', later(9289808)), CANCEL]),
        event(9289806, 'Liberation Guide: Territory Before Independence',
        'Malaya: Singapore, Kuala Lumpur, Kota Bahru, Alor Setar, Ipoh, Kuantan and Johor Bahru. Indonesia: Batavia, Tjilegon, Bandoeng, Tjirebon, Soerabaja, Jogjakarta, Malang and Madura. Vietnam: Hanoi, Dong Hoi, Da Nang, Saigon and Can Tho. Releasing an absent Philippines requires the whole Philippine minimum territory; an existing US puppet can instead gain independence after its hubs are restored. The legal owner must own the release territory, with it controlled by that owner or India.', [CANCEL]),
        event(9289807, 'Liberation Guide: Defend Suez Without Taking It',
        'Be at war with Germany or Italy while that enemy holds El Alamein, Alexandria or Cairo. Keep Suez and Port Said controlled by India, Britain or Egypt, and maintain at least three Indian land divisions in either canal province. A 30-day record begins automatically. Daily checks invalidate the attempt if the position, garrison, war or sovereign route is lost. Success gives 1,500 supplies, 150 money, +1 TC modifier and -2 dissent once. India never needs to take British ownership.', [CANCEL]),
        event(9289808, 'Liberation Guide: Northern Peace and Replacements',
        'USSR: Baku plus Tashkent or Astrakhan opens the northern settlement. Full republic territories are needed for sovereign releases. After peace with Moscow, fund reconstruction for a lasting research and supply dividend. During a Japan or Soviet war, 100 divisions and fewer than 400 manpower unlock a paid extra class: +180 manpower for 900 supplies, 100 money and +1 dissent, once per calendar year. Existing mobilisation and annual reserves still operate; a second enemy gives no second class.', [CANCEL])]
    for eid, target, key in ((9289804,'JAP','japan_war'),(9289805,'SOV','soviet_war')):
        gate = all_of(ACTIVE, war(target), no(flag(key)))
        ev.append(event(eid, f'LIBERATOR1: Indian War Against {target} Recorded',
            'This records an actual Indian war for the optional campaign. No declaration, reward or alliance change is made.', [action('Record the active war', setf(key), gate=gate)], gate=gate, automatic=True, offset=1))
    ev += regions() + china() + suez() + settlements() + manpower() + [abandoned_requests()]
    import aubm_liberator_v2 as v2
    ev = v2.revise_pack(ev, globals())
    ev += v2.render_events(globals())
    import aubm_liberator_v3 as v3
    ev = v3.revise_pack(ev)
    ev += v3.render_events()
    import aubm_siam_settlement as siam
    ev += siam.render_events()
    return MARKER + '\n\n' + '\n\n'.join(ev) + '\n# END AUBM LIBERATOR1\n'


def apply_to_bytes(original):
    import aubm_liberator_v2 as v2
    prefix = original.split(MARKER.encode('ascii'),1)[0]
    if MARKER.encode('ascii') not in original:
        prefix += b'\n' if prefix.endswith(b'\n') else b'\n\n'
    return v2.patch_legacy(prefix) + render().encode('ascii')


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    before = OUTPUT.read_bytes()
    after = apply_to_bytes(before)
    if args.check:
        if before != after: raise SystemExit('STALE: LIBERATOR3 generated events')
        print('OK: LIBERATOR3 event pack is current')
    else:
        OUTPUT.write_bytes(after)
        print('WROTE: LIBERATOR3 suffix and seven scoped legacy event revisions')


if __name__ == '__main__': main()
